package io.spaceshiva.kogito.dnd.battle.flow;

import java.util.HashMap;
import java.util.Map;

import javax.inject.Inject;
import javax.inject.Named;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;
import org.kie.kogito.Model;
import org.kie.kogito.process.Process;
import org.kie.kogito.process.ProcessInstance;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.kie.api.runtime.process.ProcessInstance.STATE_COMPLETED;

@QuarkusTest
public class WorkflowTest {

    // this is the name of the process generated by Kogito. It is the workflow id. :)
    @Named("battleflow")
    @Inject
    Process<? extends Model> battleFlow;

    @Inject
    ObjectMapper objectMapper;

    @Test
    public void testJsonServiceCallWorkflow() throws Exception {
        // TODO: set a Knative listener Emitter{channel:'kogito_outgoing_stream'} has no downstream

        assertNotNull(battleFlow);

        Model m = battleFlow.createModel();
        Map<String, Object> parameters = new HashMap<>();

        final Character player = new Character();
        player.setName("Sheldon Cooper");
        player.setArmor(5);
        player.setClazz("Nerd");
        player.setDexterity(2);
        player.setStrength(2);
        player.setHitPoints(10);

        final Character enemy = new Character();
        enemy.setName("Imppy");
        enemy.setArmor(1);
        enemy.setClazz("Imp");
        enemy.setDexterity(1);
        enemy.setStrength(1);
        enemy.setHitPoints(5);

        final Battle battle = new Battle();
        battle.setEnemy(enemy);
        battle.setPlayer(player);

        final JsonNode workflowDataInput = objectMapper.readTree(objectMapper.writeValueAsString(battle));
        parameters.put("workflowdata", workflowDataInput);
        m.fromMap(parameters);

        ProcessInstance<?> processInstance = battleFlow.createInstance(m);
        processInstance.start();
        assertEquals(STATE_COMPLETED, processInstance.status());
    }
}
